version: 2

data:
  scale_jitter_factor:
    template: 0
    search: 0.25
  translation_jitter_factor:
    template: 0
    search: 3
  gray_scale_probability: 0.05
  color_jitter: 0.4

train:
  lr: 1.e-4
  lr_backbone: 1.e-5
  batch_size: 16
  weight_decay: 1.e-4
  epochs: 1000
  lr_drop: 500
  clip_max_norm: 0.1
  optimizer: AdamW

  data:
    samples_per_epoch: 38000

  loss:
    type: transt
    parameters:
      weight:
        cross_entropy: 8.334
        bbox: 5
        giou: 2
      eos_coef: 0.0625

val:
  batch_size: 16

  data:
    repeat_times_per_epoch: 1
