backbone:
  type: alexnet
  output_layers: [ 3, 4 ]
  xcross_head: batch_norm
  position_embedding: sine
  siamfc:
    context: 0.5
    exemplar_size: 127
    instance_size: 255
transformer:
  encoder:
    num_layers: 6
    num_reference_points: 4
  decoder:
    num_layers: 6
    num_reference_points: 4
  feed_forward:
    dim: 1024
  hidden_dim: 256
  dropout: 0.1
  num_heads: 8
  num_queries: 64
