version: 2

data:
  scale_jitter_factor:
    template: 0
    search: 0.25
  translation_jitter_factor:
    search: 3
    template: 0
  gray_scale_probability: 0.05
  color_jitter: 0.4
  gaussian_target_label_min_overlap: 0.7

train:
  lr: 1.e-4
  lr_backbone: 1.e-5
  batch_size: 16
  weight_decay: 1.e-4
  epochs: 1000
  lr_drop: 500
  clip_max_norm: 0.1
  optimizer: AdamW

  data:
    repeat_times_per_epoch: 2

  loss:
    type: exp-1
    parameters:
      target_classification:
        gaussian_focal_loss:
          weight: 9
      bounding_box_regression:
        l1:
          weight: 3
        IoU:
          type: CIoU
          weight: 1
      quality_assessment:
        IoU_aware:
          type: CIoU
          weight: 1.75

val:
  batch_size: 16

  data:
    repeat_times_per_epoch: 1
