META_ARC: 'siamrpn_r50_l234_dwxcorr'
CUDA: true

TRAIN:
  # anchors
  THR_HIGH: 0.6
  THR_LOW: 0.3
  NEG_NUM: 16
  POS_NUM: 16
  TOTAL_NUM: 64

  EXEMPLAR_SIZE: 127
  SEARCH_SIZE: 255
  BASE_SIZE: 8
  OUTPUT_SIZE: 25

  RESUME: ''
  PRETRAINED: ''
  LOG_DIR: './logs'
  SNAPSHOT_DIR: './snapshot'

  EPOCH: 20
  START_EPOCH: 0
  BATCH_SIZE: 32
  NUM_WORKERS: 1

  # optimizer
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  CLS_WEIGHT: 1.0
  LOC_WEIGHT: 1.2
  MASK_WEIGHT: 1
  PRINT_FREQ: 20
  LOG_GRADS: false
  GRAD_CLIP: 10.0
  BASE_LR: 0.005
  LR:
    TYPE: 'log'

  LR_WARMUP:
    WARMUP: true
    TYPE: 'step'
    EPOCH: 5

DATASET:
  TEMPLATE:
    SHIFT: 4
    SCALE: 0.05
    BLUR: 0.0
    FLIP: 0.0
    COLOR: 1.0
  SEARCH:
    SHIFT: 64
    SCALE: 0.18
    BLUR: 0.0
    FLIP: 0.0
    COLOR: 1.0

  NEG: 0.2
  GRAY: 0.0
  NAMES: ['VID', 'COCO', 'DET', 'YOUTUBEBB']
  VID:
    ROOT: 'training_dataset/vid/crop511'
    ANNO: 'training_dataset/vid/train.json'
    FRAME_RANGE: 100
    NUM_USE: 100000
  YOUTUBEBB:
    ROOT: 'training_dataset/yt_bb/crop511'
    ANNO: 'training_dataset/yt_bb/train.json'
    FRAME_RANGE: 3
    NUM_USE: -1
  COCO:
    ROOT: 'training_dataset/coco/crop511'
    ANNO: 'training_dataset/coco/train2017.json'
    FRAME_RANGE: 1
    NUM_USE: -1
  DET:
    ROOT: 'training_dataset/det/crop511'
    ANNO: 'training_dataset/det/train.json'
    FRAME_RANGE: 1
    NUM_USE: -1

  VIDEOS_PER_EPOCH: 600000

BACKBONE:
  TYPE: 'res50'
  PRETRAINED: ''
  TRAIN_LAYERS: ['layer2', 'layer3', 'layer4']
  LAYERS_LR: 0.1
  TRAIN_EPOCH: 10

ADJUST:
  ADJUST: true
  TYPE: 'AdjustAllLayer'

RPN:
  TYPE: 'MultiRPN'

MASK:
  MASK: false
  TYPE: 'MaskCorr'

REFINE:
  REFINE: false
  TYPE: 'Refine'

ANCHOR:
  STRIDE: 8
  RATIOS: [0.33, 0.5, 1, 2, 3]
  SCALES: [8]
  ANCHOR_NUM: 5 # len(ANCHOR.RATIOS) * len(ANCHOR.SCALES)

TRACK:
  TYPE: 'SiamRPNTracker'
  PENALTY_K: 0.04
  WINDOW_INFLUENCE: 0.44
  LR: 0.4
  EXEMPLAR_SIZE: 127
  INSTANCE_SIZE: 255
  BASE_SIZE: 8
  CONTEXT_AMOUNT: 0.5
  LOST_INSTANCE_SIZE: 831 # Long term lost search size
  CONFIDENCE_LOW: 0.85
  CONFIDENCE_HIGH: 0.998
  MASK_THERSHOLD: 0.30
  MASK_OUTPUT_SIZE: 127
