version: 2

data:
  scale_jitter_factor:
    template: 0
    search: 0.25
  translation_jitter_factor:
    search: 3
    template: 0
  gray_scale_probability: 0.05
  color_jitter: 0.4
  gaussian_target_label_min_overlap: 0.7

train:
  lr: 1.e-4
  lr_backbone: 1.e-5
  batch_size: 16
  weight_decay: 1.e-4
  epochs: 1000
  lr_drop: 500
  clip_max_norm: 0.1
  optimizer: AdamW

  data:
    samples_per_epoch: 38000

  loss:
    classification:
      gaussian_focal_loss:
        weight: 500
    bounding_box_regression:
      smooth_L1_loss:
        beta: 0.25
        weight: 10
      IoU_loss:
        type: CIoU
        weight: 1

val:
  batch_size: 16

  data:
    repeat_times_per_epoch: 1
