version: 2

dataloader:
  version: old

data:
  scale_jitter_factor:
    template: 0
    search: 0.25
  translation_jitter_factor:
    search: 3
    template: 0
  gray_scale_probability: 0.05
  color_jitter: 0.4

train:
  lr: 1.e-4
  lr_backbone: 1.e-5
  batch_size: 2
  weight_decay: 1.e-4
  epochs: 1000
  lr_drop: 500
  clip_max_norm: 0.1
  optimizer: AdamW

  data:
    samples_per_epoch: 38000
    negative_sample_ratio: 0.

  loss:
    use_template: transt

val:
  batch_size: 2

  data:
    repeat_times_per_epoch: 1
