version: 4

data:
  augmentation:
    scale_jitter_factor:
      template: 0
      search: 0.25
    translation_jitter_factor:
      template: 0
      search: 3
    gray_scale_probability: 0.05
    color_jitter: 0.4
    stage_2_on_host_process: ture

  sampler:
    version: 2

    train:
      batch_size: 64

      samples_per_epoch: 131072
      negative_sample_ratio: 0

      sequence_sampler:
        type: "Siamese"
        parameters:
          frame_range: 100
          enforce_fine_positive_sample: true
          enable_adaptive_frame_range: true
          sampling_method: "interval"

    val:
      batch_size: 64

      samples_per_epoch: 4096
      negative_sample_ratio: 0

      sequence_sampler:
        type: "Siamese"
        parameters:
          frame_range: 100
          enforce_fine_positive_sample: true
          enable_adaptive_frame_range: true
          sampling_method: "interval"

optimization:
  epochs: 45
  optimizer:
    type: "AdamW"
    lr: 1.e-4
    advanced_strategy:
      type: "Backbone-Pretrained"
      lr_backbone: 1.e-5
    weight_decay: 1.e-4
    clip_max_norm: 0.1
    lr_scheduler:
      type: "MultiStepLR"
      values: [1, 0.1, 0.01]
      milestones: [0.33, 0.66, 1]
      per_iteration: true

      warmup:
        initial_factor: 0.001
        length: 0.01
        method: "linear" # linear or constant

  loss:
    classification:
      post_filter:
        type: "reweight_by_num_pos"
      quality_focal:
        beta: 2
        quality_function: "IoU"
        display_name: "loss_quality_focal"
        reduce: "sum"
        weight:
          scheduler: "linear"
          initial_value: 0
          ultimate_value: 1
          length: 0.1
          per_iteration: true
      binary_cross_entropy:
        display_name: "loss_bce"
        reduce: "sum"
        weight:
          scheduler: "linear"
          initial_value: 1
          ultimate_value: 0
          length: 0.1
          per_iteration: true
    bbox_regression:
      pre_filter:
        type: "positive_only_and_generate_weight_by_classification_score"
      post_filter:
        type: "reweight_by_sample_weight"
      distribution_focal:
        display_name: "loss_distribution_focal"
        reduce: "weighted"
        weight: 0.25
      IoU:
        type: "GIoU"
        display_name: "loss_iou"
        reduce: "weighted"
        weight: 2.0
