backbone:
  type: alexnet
  position_embedding: sine
  siamfc:
    context: 0.5
    exemplar_size: 127
    instance_size_limit: 200
transformer:
  encoder:
    num_layers: 6
  decoder:
    num_layers: 6
  feed_forward:
    dim: 2048
  hidden_dim: 256
  dropout: 0.1
  num_heads: 8
  num_queries: 64
  z_feats: 36
