data:
  area_factor:
    template: 2.0
    search: 4.0
  feature_size:
    template: [16, 16]
    search: [32, 32]
  template_size: [128, 128] # 16 * 8
  search_size: [256, 256] # 32 * 8

backbone:
  type: resnet50
  position_embedding: sine
  output_layers: [3]

transformer:
  position_embedding: sine
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  dim_feedforward: 2048
  featurefusion_layers: 4
  activation: relu