version: 3

data:
  augmentation:
    scale_jitter_factor:
      template: 0
      search: 0.25
    translation_jitter_factor:
      template: 0
      search: 3
    gray_scale_probability: 0.05
    color_jitter: 0.4
    stage_2_on_host_process: ture

  sampler:
    version: 2

    train:
      batch_size: 64

      samples_per_epoch: 131072
      negative_sample_ratio: 0

      sequence_sampler:
        type: "Siamese"
        parameters:
          frame_range: 100
          enforce_fine_positive_sample: true
          enable_adaptive_frame_range: true
          sampling_method: "causal"

    val:
      batch_size: 64

      samples_per_epoch: 16384
      negative_sample_ratio: 0.3

      sequence_sampler:
        type: "Siamese"
        parameters:
          frame_range: 100
          enforce_fine_positive_sample: false
          enable_adaptive_frame_range: true
          sampling_method: "causal"

optimization:
  epochs: 300
  optimizer:
    type: "AdamW"
    lr: 1.e-4
    lr_backbone: 1.e-5
    weight_decay: 1.e-4
    clip_max_norm: 0.1
    lr_scheduler:
      type: StepLR
      lr_drop: 150


  loss:
    quality_focal_loss:
      disp_name: "loss_quality_focal"
      beta: 2
      quality_function: "IoU"
      weight:
        scheduler: "linear"
        init_value: 0
        ultimate_value: 1
        length: 10000
        per_iter: true
    binary_cross_entropy_loss:
      disp_name: "loss_bce"
      weight:
        scheduler: "linear"
        init: 1
        ultimate: 0
        length: 10000
        per_iter: true
    distribution_focal_loss:
      disp_name: "loss_distribution_focal"
      weight: 0.25
    iou_loss:
      disp_name: "loss_iou"
      type: "GIoU"
      weight: 2.0
