name: SiamFC-GOT

version: 4
type: "SiamFCDualPath"

data:
  area_factor:
    template: 2.0
    search: 4.0
  template_size: [128, 128]
  search_size: [256, 256]

backbone:
  type: Alexnet-BN
  output_layers: [4]

neck:
  type: DualPathXCorr
  parameters:
    input_dim: 256
    hidden_dim: 256

#head:
#  type: Stark
#  parameters:
#    input_size: [7, 7]
#    input_dim: 256
#    classification:
#      type: MLP
#      parameters:
#        hidden_dim: 256
#    localization:
#      type: CornerPredictor
#      parameters:
#        hidden_dim: 256
head:
  type: DETR
  parameters:
    input_size: [17, 17]
    input_dim: 256
    hidden_dim: 256
