tracking:
  exemplar_sz: 127
  instance_sz: 255
  context: 0.5
  min_size_factor: 0.2
  max_size_factor: 5
  scale_num: 3
  scale_step: 1.0375
  scale_lr: 0.59
  scale_penalty: 0.9745
  window_influence: 0.176
  response_sz: 17
  response_up: 16
  exemplar_lr: 0
  total_stride: 8
