name: SiamFC-GOT

version: 3
type: SiamFC

data:
  area_factor:
    template: 2.0
    search: 4.0
  template_size: [112, 112]
  search_size: [224, 224]

backbone:
  type: alexnet-bn

neck:
  type: XCross

head:
  type: Stark
  parameters:
    input_size: [7, 7]
    input_dim: 256
    sub_type: StarkS
    classification:
      type:
    localization:
      type: CornerPredictor
      parameters:
        hidden_dim: 256
