version: 3

data:
  augmentation:
    scale_jitter_factor:
      template: 0
      search: 0.25
    translation_jitter_factor:
      search: 3
      template: 0
    gray_scale_probability: 0.05
    color_jitter: 0.4

  sampler:
    version: 2

    train:
      batch_size: 16
      repeat_times_per_epoch: 2

      sequence_sampler:
        type: Siamese
        parameter:
          frame_range: 100

    val:
      batch_size: 16
      repeat_times_per_epoch: 1

      sequence_sampler:
        type: Siamese
        parameter:
          frame_range: 100

optimization:
  epochs: 50
  checkpoint_interval: 10
  model_initialization: xavier
  optimizer:
    type: SGD
    lr: 1.e-3
    lr_backbone: 1.e-4
    weight_decay: 5.e-4
    momentum: 0.9
    nesterov: true
    lr_scheduler:
      type: ExponentialLR
      ultimate_lr: 1.e-5

  loss:
    type: balanced
