FILTERS:
  DATA_CLEANING:
    AnnotationStandard:
      bounding_box_format: XYXY
      pixel_coordinate_system: Aligned
      bounding_box_coordinate_system: Spatial
      pixel_definition: Point
    BoundingBox:
      fit_in_image_size: true
      update_validity: true
      remove_invalid_objects: true
      remove_empty_objects: true
    Integrity:
      remove_zero_annotation_image: true
      remove_zero_annotation_video_head_tail: true
      remove_invalid_image: true

CONFIG:
  dump_human_readable: false
  cache_meta_data: false

DATASETS:
  GOT10k:
    SPLITS:
      - train

  LaSOT:
    SPLITS:
      - train
  YoutubeBB:

  COCO:
    Sampling:
      weight: 0.5

  ILSVRC_DET:
    Sampling:
      weight: 0.5

  ILSVRC_VID:
    Sampling:
      weight: 0.5
