classification:
  gaussian_focal_loss:
    weight: 9
bounding_box_regression:
  smooth_L1_loss:
    weight: 10
  IoU_loss:
    type: CIoU
    weight: 1
quality_assessment:
  IoU_aware_loss:
    type: CIoU
    weight: 1.75
