parameters:
  classification:
    cross_entropy_loss:
      num_classes: 1
      background_class_weight: 0.0625
      weight: 8.334
  bounding_box_regression:
    IoU_loss:
      type: GIoU
      weight: 2
    L1_loss:
      weight: 5
